[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_NODE_ENV = "production"

[context.deploy-preview.environment]
  VITE_NODE_ENV = "development"

[context.branch-deploy.environment]
  VITE_NODE_ENV = "development"

[build.processing.secrets]
  # Lista de claves que el escáner de Netlify debe ignorar.
  # ¡Asegúrate de que estas claves realmente pueden ser públicas!
  omit_keys = [
    "VITE_FIREBASE_API_KEY",
    "VITE_FIREBASE_AUTH_DOMAIN",
    "VITE_FIREBASE_PROJECT_ID",
    "VITE_FIREBASE_STORAGE_BUCKET",
    "VITE_FIREBASE_MESSAGING_SENDER_ID",
    "VITE_FIREBASE_APP_ID",
    "VITE_FIREBASE_MEASUREMENT_ID",
    "VITE_GOOGLE_CLIENT_ID"
  ]
  # Omitir archivos de build donde aparecen estos valores
  omit_paths = [
    "dist/**/*"
  ]
