[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_NODE_ENV = "production"

[context.deploy-preview.environment]
  VITE_NODE_ENV = "development"

[context.branch-deploy.environment]
  VITE_NODE_ENV = "development"
